######################################## default parameters ####################################################

# playground image
playgroundImage = "/images/playground.jpg"

# lived-in image
livedInImage = "/images/lived-in.png"
countries_i_visited = "Countries I Visited"
playground = "Playground"
colortheme = "white" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = false # default

# Home page settings
description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."

mainSection = "posts" # your main section
showAllPostsOnHomePage = false # default
postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true`
tagsOverview = true # show tags overview by default.
showProjectsList = true # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/gohugoio" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true # default
showReadTime = true # default

[comments]
enabled = true # default
engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
[comments.utterances]
repo = "<github_username>/<github_reponame>"
label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
theme = "github-light"
[comments.cactuscomments]
siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
#serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
#serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[social]]
name = "github"
link = "https://github.com/gohugoio"
[[social]]
name = "linkedin"
link = "https://www.linkedin.com/company/github/"
[[social]]
name = "email"
link = "example@example.com" # no need for "mailto:" in the head
